version: "3"
services:
  jenkins:
    image: cowell/jenkins:1.0.0
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
        - /data/jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins-docker
